### ISSUE TITLE
Find Alternative Camera Image Control Mechanism

### ISSUE THREAD

**Issue by FormerLurker** [FormerLurker/Octolapse#426]
Custom image preferences are great, but rely on mjpgstreamer's control.htm page to receive camera control commands.  Find an alternative method for both detecting the camera's control ability and for updating each control that will work more generally for cameras directly attached via USB to the host (hopefully for Linux, Windows and Mac).

Would solve #424.

**Comment by RaymondHimle** [comment]
@FormerLurker Some input of the referenced issue would be very helpful. We could use some help figuring out a good way to allow users to use both OctoLapse and TSD's 25FPS streaming

**Comment by FormerLurker** [comment]
I have posted a comment.  Once v0.4 is released I'd be interested in cooperating on this.  I think implementing H.264 in TSD is a great feature, and I'd love for these two plugins to play nicely with each other!

**Comment by bjhiltbrand** [comment]
Is there an update on this? I just re-imaged my Raspberry Pi, and as such, installed the latest Octolapse and Spaghetti Detective plugins. However, Octolapse fails to load settings or work at all as long as The Spaghetti Detective is active. Now that v0.4 is released, has there been any progress made on making the 2 plugins play nice together? Thanks.

**Comment by FormerLurker** [comment]
Yes, TSD has included a compatibility mode that should work.  Check your TSD settings and give it a go.  Let me know how it goes!

**Comment by bjhiltbrand** [comment]
Wow! That was a fast response! Thank you for that. I re-enabled the TSD plugin took a look at the settings. I think I found the setting that you mentioned. It was set to the default option of "Automatic". I changed it to always in compatibility mode and restarted, but still seem to have issues with Octolapse being unable to load when TSD is active.

![chrome_hc8rUR8rtO](https://user-images.githubusercontent.com/11344821/86059889-ee6c0d80-ba20-11ea-955d-200729cf7967.png)
![chrome_uaXsnaZKGQ](https://user-images.githubusercontent.com/11344821/86059898-f166fe00-ba20-11ea-86ab-72b264551821.png)

**Comment by RaymondHimle** [comment]
Make sure you completely reboot your raspberry pi after changing to compatibly mode

**Comment by bjhiltbrand** [comment]
Wow! That was a fast response! Thank you for that. I re-enabled the TSD plugin took a look at the settings. I think I found the setting that you mentioned. It was set to the default option of "Automatic". I changed it to always in compatibility mode and restarted, but still seem to have issues with Octolapse being unable to load when TSD is active.

![chrome_hc8rUR8rtO](https://user-images.githubusercontent.com/11344821/86060240-941f7c80-ba21-11ea-88ad-67674e897080.png)
![chrome_uaXsnaZKGQ](https://user-images.githubusercontent.com/11344821/86060242-971a6d00-ba21-11ea-9c26-4029919dc236.png)

**Comment by FormerLurker** [comment]
That is an odd error message for this situation, and i am a bit baffled by it.  As the other poster said, do a full reboot first.  If you still see the same error, please post your plugin_octolapse.log file.

**Comment by RaymondHimle** [comment]
Also feel free to ask for help on the TSD Discord as it should be working on compatibly mode.

**Comment by bjhiltbrand** [comment]
I did a reboot, and full shutdown/power off. The issue still remains.

Here is my log file. Doesn't look like there's anything out of the ordinary.
[plugin_octolapse.log](https://github.com/FormerLurker/Octolapse/files/4848264/plugin_octolapse.log)

**Comment by bjhiltbrand** [comment]
@RaymondHimle, I'm just catching up on the discord group, as I haven't been in there for a while. I'll see if others have been in this situation.

**Comment by FormerLurker** [comment]
Fyi, i am in the process of updating the plugin documents for TSD and Octoprint Anywhere to reflect the changes.  Things have been a bit crazy lately, and I have been delayed over and over.  I WILL get to it ASAP.

**Comment by FormerLurker** [comment]
Check the browser console for errors please.  F12 usually opens the console.

**Comment by bjhiltbrand** [comment]
![chrome_EjrIYHxU2Z](https://user-images.githubusercontent.com/11344821/86061020-2a07d700-ba23-11ea-9a61-440e1f45299b.png)

**Comment by FormerLurker** [comment]
Lots of 503 (permission errors) responses there.  Can you export and post settings.json (octoprint settings->Octolapse->export settings)?  I can review it tomorrow.

**Comment by bjhiltbrand** [comment]
[settings.zip](https://github.com/FormerLurker/Octolapse/files/4848353/settings.zip)

Apparently, github won't let you upload json files on their own, please unzip to find the file you're after. Thank you so much for being so responsive. I really appreciate it. Have a good night.

**Comment by FormerLurker** [comment]
For future reference, upload these to gist.github.com.  thanks!
